In [1]:
import numpy as np
import numpy.linalg as la

verySmallNumber = 1e-14


In [2]:
V = np.array([[1,0,2,6],
             [0,1,8,2],
             [2,8,3,1],
             [1,-6,2,3]], dtype=np.float_)

In [3]:
V

array([[ 1.,  0.,  2.,  6.],
       [ 0.,  1.,  8.,  2.],
       [ 2.,  8.,  3.,  1.],
       [ 1., -6.,  2.,  3.]])

In [4]:
V[:,0]

array([1., 0., 2., 1.])

In [5]:
V[:,1]

array([ 0.,  1.,  8., -6.])

In [36]:
# Our first function will perform the Gram-Schmidt procedure for 4 basis vectors.
# We'll take this list of vectors as the columns of a matrix, A.
# We'll then go through the vectors one at a time and set them to be orthogonal 
# to all the vectors that came before it.  Before normalising.

def gsBasis4(A):
    B = np.array(A, dtype=np.float_) # Make B a copy of A, since we're going to alter it's values.
    # The zeroth column is easy since it has no other vectors to make it normal to.
    # All that needs to be done is to normalise it. i.e. divide by its modulus, or norm.
    B[:,0] = B[:,0] / la.norm(B[:,0])
    
    # For the 1st column, we need to subtract any overlap with our new zeroth vector.
    B[:,1] = B[:,1] - B[:,1] @ B[:,0] * B[:,0]
    # If there is anything left after that subtraction, then B[:,1] is linearly independent of B[:,0]
    # If this is the case, we can normalise it. Otherwise, we'll set that vector to zero.
    if la.norm(B[:,1]) > verySmallNumber:
        B[:,1] = B[:,1] / la.norm(B[:,1])
    else:
        B[:,1] = np.zeros_like(B[:,1])
        
    # Now we need to repeat the process for column 2.
    # Insert two lines of code, the first to subtract the overlap with the zeroth vector,
    # and the second to subtract the overlap with the first.
    B[:,2] = B[:,2] - B[:,2] @ B[:,0] * B[:,0]
    B[:,2] = B[:,2] - B[:,2] @ B[:,1] * B[:,1]
    
    # Again we'll need to normalise our new vector.
    # Copy and adapt the normalisation fragment from above to column 2.
    if la.norm(B[:,2]) > verySmallNumber :
        B[:,2] = B[:,2] / la.norm(B[:,2])
    else :
        B[:,2] = np.zeros_like(B[:,2])
    
    # Finally, column three:
    # Insert code to subtract the overlap with the first three vectors.
    B[:,3] = B[:,3] - B[:,3] @ B[:,0] * B[:,0]
    B[:,3] = B[:,3] - B[:,3] @ B[:,1] * B[:,1]
    B[:,3] = B[:,3] - B[:,3] @ B[:,2] * B[:,2]
    
    # Now normalise if possible
    if la.norm(B[:,3]) > verySmallNumber :
        B[:,3] = B[:,3] / la.norm(B[:,3])
    else :
        B[:,3] = np.zeros_like(B[:,3])
    
    return B

In [59]:
def gsBasis3(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    # The zeroth column is easy, since it has no other vectors to make it normal to.
    # All that needs to be done is to normalise it. I.e. divide by its modulus, or norm.
    B[:, 0] = B[:, 0] / la.norm(B[:, 0])
    # For the first column, we need to subtract any overlap with our new zeroth vector.
    B[:, 1] = B[:, 1] - B[:, 1] @ B[:, 0] * B[:, 0]
    # If there's anything left after that subtraction, then B[:, 1] is linearly independant of B[:, 0]
    # If this is the case, we can normalise it. Otherwise we'll set that vector to zero.
    if la.norm(B[:, 1]) > verySmallNumber :
        B[:, 1] = B[:, 1] / la.norm(B[:, 1])
    else :
        B[:, 1] = np.zeros_like(B[:, 1])
    # Now we need to repeat the process for column 2.
    # Insert two lines of code, the first to subtract the overlap with the zeroth vector,
    # and the second to subtract the overlap with the first.
    B[:,2] = B[:,2] - B[:,2] @ B[:,0] * B[:,0]
    B[:,2] = B[:,2] - B[:,2] @ B[:,1] * B[:,1]    
    
    # Again we'll need to normalise our new vector.
    # Copy and adapt the normalisation fragment from above to column 2.
    if la.norm(B[:,2]) > verySmallNumber :
        B[:,2] = B[:,2] / la.norm(B[:,2])
    else :
        B[:,2] = np.zeros_like(B[:,2])    
       
    # Finally, we return the result:
    return B

In [75]:
# The second part of this exercise will generalise the procedure.
# Previously, we could only have four vectors, and there was a lot of repeating in the code.
# We'll use a for-loop here to iterate the process for each vector.
def gsBasis(A):
    B = np.array(A, dtype=np.float_) # Make B a copy of A, since we're going to alter it's values.
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]):
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i):
            # Complete the code to subract the overlap with previous vectors.
            # You'll need the current vector B[:,i] and a previous vector B[:,j]
            B[:,i] = B[:,i] - B[:,i] @ B[:,j] * B[:,j]
        # Next insert code to do the normalisation test for B[:,i]
        if la.norm(B[:,i]) > verySmallNumber :
            B[:,i] = B[:,i] / la.norm(B[:,i])
        else :
            B[:,i] = np.zeros_like(B[:,i])
    # Finally return the result
    return B

In [49]:
# This function uses the Gram-Schmidt process to calculate the dimension 
# spanned by a list of vectors.
# Since each vector is normalised to one, or is zero, 
# the sum of all the norms will be the dimension
def dimension(A):
    return np.sum(la.norm(gsBasis(A), axis = 0))

In [40]:
Vp = gsBasis4(V); Vp

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [41]:
la.norm(Vp[:,3])

1.0

In [31]:
Vp.shape

(4, 4)

In [35]:
gsBasis(V)

array([[ 0.40824829, -0.1814885 ,  0.04982278,  0.89325973],
       [ 0.        ,  0.1088931 ,  0.99349591, -0.03328918],
       [ 0.81649658,  0.50816781, -0.06462163, -0.26631346],
       [ 0.40824829, -0.83484711,  0.07942048, -0.36063281]])

In [44]:
U = np.array([[0,0,1],
             [0,1,1],
             [1,1,0],
             [1,0,0]], dtype=np.float_)

In [45]:
U

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 1., 0.],
       [1., 0., 0.]])

In [46]:
gsBasis(U)

array([[ 0.        ,  0.        ,  0.8660254 ],
       [ 0.        ,  0.81649658,  0.28867513],
       [ 0.70710678,  0.40824829, -0.28867513],
       [ 0.70710678, -0.40824829,  0.28867513]])

In [56]:
dimension(V)

4.0

In [58]:
la.norm(gsBasis(V), axis=0)

array([1., 1., 1., 1.])

In [61]:
# Now let's see what happens when we have one vector that is a linear combination of the others.
C = np.array([[1,0,2],
              [0,1,-3],
              [1,0,2]], dtype=np.float_)
gsBasis3(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [76]:
gsBasis(C)

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.70710678, 0.        , 0.        ]])

In [64]:
la.norm(gsBasis3(C), axis=0)

array([1., 1., 0.])

In [74]:
for i in range(C.shape[1]): 
    for j in range(i):
        print(i,j)

1 0
2 0
2 1


In [68]:
i

range(0, 3)

In [71]:
for j in range(i): print(j)

0
1
